title: dynardl
description: Stata module to dynamically simulate autoregressive distributed lag (ARDL) models.
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
